"""add blog cms tables

Revision ID: 1a4a26642c93
Revises: 9406e1d86cfe
Create Date: 2026-09-02 10:43:55.238052

"""
from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision = '1a4a26642c93'
down_revision = '9406e1d86cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('blog_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_categories_slug'), ['slug'], unique=True)

    op.create_table('blog_tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=70), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('blog_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_tags_slug'), ['slug'], unique=True)

    op.create_table('blog_posts',
    sa.Column('author_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('markdown_body', sa.Text(), nullable=False),
    sa.Column('rendered_body', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('category_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'scheduled')", name='ck_blog_posts_status_valid'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_posts_status'), ['status'], unique=False)

    op.create_table('blog_post_tags',
    sa.Column('post_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('tag_id', app.models.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post_tags')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_status'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_category_id'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_author_id'))

    op.drop_table('blog_posts')
    with op.batch_alter_table('blog_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_tags_slug'))

    op.drop_table('blog_tags')
    with op.batch_alter_table('blog_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_categories_slug'))

    op.drop_table('blog_categories')
    # ### end Alembic commands ###
