"""add portfolio content tables

Revision ID: 2f37f4959076
Revises: 03c629ad4d1e
Create Date: 2026-09-02 07:52:10.744258

"""
from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision = '2f37f4959076'
down_revision = '03c629ad4d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profiles',
    sa.Column('user_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('professional_title', sa.String(length=150), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('location_text', sa.String(length=150), nullable=True),
    sa.Column('availability_text', sa.String(length=150), nullable=True),
    sa.Column('public_email', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('skills',
    sa.Column('category_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.CheckConstraint('proficiency >= 1 AND proficiency <= 5', name='ck_skills_proficiency_range'),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category_id'), ['category_id'], unique=False)

    op.create_table('achievements',
    sa.Column('profile_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=True),
    sa.Column('achievement_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_profile_id'), ['profile_id'], unique=False)

    op.create_table('certifications',
    sa.Column('profile_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=150), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_profile_id'), ['profile_id'], unique=False)

    op.create_table('educations',
    sa.Column('profile_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('field', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grade_summary', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_educations_profile_id'), ['profile_id'], unique=False)

    op.create_table('experiences',
    sa.Column('profile_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_profile_id'), ['profile_id'], unique=False)

    op.create_table('projects',
    sa.Column('profile_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('resumes',
    sa.Column('profile_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('storage_reference', sa.String(length=500), nullable=True),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('download_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_profile_id'), ['profile_id'], unique=True)

    op.create_table('social_links',
    sa.Column('profile_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_links_profile_id'), ['profile_id'], unique=False)

    op.create_table('project_technologies',
    sa.Column('project_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_technologies_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_technologies_project_id'))

    op.drop_table('project_technologies')
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_links_profile_id'))

    op.drop_table('social_links')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_profile_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_profile_id'))

    op.drop_table('projects')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_profile_id'))

    op.drop_table('experiences')
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_educations_profile_id'))

    op.drop_table('educations')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_profile_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_profile_id'))

    op.drop_table('achievements')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_category_id'))

    op.drop_table('skills')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    op.drop_table('skill_categories')
    # ### end Alembic commands ###
