"""add navigation items table

Revision ID: 9406e1d86cfe
Revises: eda62625c94d
Create Date: 2026-09-02 09:42:40.201572

"""
from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision = '9406e1d86cfe'
down_revision = 'eda62625c94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_items',
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('navigation_items')
    # ### end Alembic commands ###
