"""add portfolio templates table

Revision ID: eda62625c94d
Revises: 2f37f4959076
Create Date: 2026-09-02 08:46:15.432200

"""
from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision = 'eda62625c94d'
down_revision = '2f37f4959076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_templates',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_templates_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_templates_key'))

    op.drop_table('portfolio_templates')
    # ### end Alembic commands ###
